dbproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('events.urls')),
]

events/urls.py
from django.urls import include, path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'events'
urlpatterns = [
    path('', views.WelcomeView.as_view(), name='welcome'),
    path('login/', LoginView.as_view(template_name='events/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegistrationView.as_view(), name='register'),
    path('home/', views.HomeView.as_view(), name='home'),
    path('viewUser/<int:pk>/', views.ViewUser.as_view(), name='viewUser'),
    path('editUser/<int:pk>/', views.EditUser.as_view(), name='editUser'),
    path('universities/', views.UniversityList.as_view(), name='universities'),
    path('addUniversity/', views.AddUniversity.as_view(), name='addUniversity'),
    path('viewUniversity/<int:pk>/', views.ViewUniversity.as_view(), name='viewUniversity'),
    path('editUniversity/<int:pk>/', views.EditUniversity.as_view(), name='editUniversity'),
    path('addEvent/', views.AddEvent.as_view(), name='addEvent'),
    path('viewEvent/<int:pk>/', views.ViewEvent.as_view(), name='viewEvent'),
    path('editEvent/<int:pk>/', views.EditEvent.as_view(), name='editEvent'),
    path('addComment/', views.AddComment.as_view(), name='addComment'),
    path('editComment/<int:pk>/', views.EditComment.as_view(), name='editComment'),
    path('deleteComment/<int:pk>/', views.DeleteComment.as_view(), name='deleteComment'),
    path('RSOs/', views.RSOList.as_view(), name='RSOs'),
    path('addRSO/', views.AddRSO.as_view(), name='addRSO'),
    path('viewRSO/<int:pk>/', views.ViewRSO.as_view(), name='viewRSO'),
    path('editRSO/<int:pk>/', views.EditRSO.as_view(), name='editRSO'),
]

events/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse, reverse_lazy
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

# Create your models here.
class University(models.Model):
    name = models.CharField(max_length=20, unique=True)
    location = models.CharField(max_length=100)
    desc = models.TextField()
    num_students = models.IntegerField()
    superadmin = models.ForeignKey('User', on_delete=models.CASCADE, default='', related_name='superadmin')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('events:universities')

class User(AbstractUser):
    PERM_LEVELS = (
        ('Student', 'Student'),
        ('Admin', 'Admin'),
        ('Superadmin', 'Superadmin'),
    )
    
    university = models.ForeignKey(University, on_delete=models.CASCADE, default='', null=True, blank=True)
    rsos = models.ManyToManyField('RSO', blank=True)
    name = models.CharField(max_length=20)
    email = models.EmailField()
    perm_level = models.CharField(max_length=10, choices=PERM_LEVELS, null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('events:viewUser', kwargs={'pk': self.pk})

class RSO(models.Model):
    name = models.CharField(max_length=20, unique=True)
    num_students = models.IntegerField()
    university = models.ForeignKey(University, on_delete=models.CASCADE, default='')
    admin = models.ForeignKey(User, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('events:viewRSO', kwargs={'pk': self.pk})
    
    def save(self, *args, **kwargs):
        if self.num_students > 4:
            self.is_active = True
        else:
            self.is_active = False
        super().save(*args, **kwargs)

class Event(models.Model):
    CATEGORIES = (
        ('Social', 'Social'),
        ('Educational', 'Educational'),
        ('Food', 'Food'),
        ('Fun', 'Fun'),
    )

    EVENT_TYPES = (
        ('RSO', 'RSO'),
        ('Private', 'Private'),
        ('Public', 'Public'),
    )
    
    host = models.ForeignKey(User, on_delete=models.CASCADE, related_name='host')
    time = models.DateTimeField()
    location = models.CharField(max_length=100)
    university = models.ForeignKey(University, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=20)
    category = models.CharField(max_length=15, choices=CATEGORIES)
    desc = models.TextField()
    contact_phone = models.CharField(max_length=20)
    contact_email = models.EmailField()
    commenters = models.ManyToManyField(User, through='Comment')
    host_rso = models.ForeignKey(RSO, on_delete=models.CASCADE, default='', blank=True, null=True)
    event_type = models.CharField(max_length=7, choices=EVENT_TYPES, null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('events:viewEvent', kwargs={'pk': self.pk})
    
    def clean(self):
        if self.host_rso is not None and self.host != self.host_rso.admin:
            raise ValidationError(_('You are not the admin of this RSO, so you are not allowed to create an event for it.'))

    class Meta:
        unique_together = ('time', 'location')

class Comment(models.Model):
    RATINGS = (
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
    )
    
    text = models.TextField()
    rating = models.IntegerField(choices=RATINGS)

    created_by = models.ForeignKey(User, on_delete=models.CASCADE, editable=False)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.text

    def get_absolute_url(self):
        return reverse('events:viewEvent', kwargs={'pk': self.event.pk})

events/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import User, University, RSO, Event, Comment

class MyUserCreationForm(UserCreationForm):
    PERM_LEVELS = (
        ('Student', 'Student'),
        ('Admin', 'Admin'),
        ('Superadmin', 'Superadmin'),
    )
    
    name = forms.CharField(max_length=20)
    email = forms.EmailField()
    perm_level = forms.ChoiceField(choices=PERM_LEVELS)
    university = forms.ModelChoiceField(queryset=University.objects.all(), to_field_name='name', empty_label=None, required=False)

    class Meta:
        model = User
        fields = UserCreationForm.Meta.fields + ('name', 'email', 'perm_level', 'university',)

class EditUserForm(forms.ModelForm):
    rsos = forms.ModelMultipleChoiceField(queryset=RSO.objects.all(), to_field_name='name', required=False, widget=forms.CheckboxSelectMultiple)

    class Meta:
        model = User
        fields = ['name', 'email', 'university', 'rsos']

class AddEventForm(forms.ModelForm):
    time = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}), required=True, input_formats=['%Y-%m-%dT%H:%M',])
    
    class Meta:
        model = Event
        fields = ['host', 'time', 'location', 'university', 'name', 'category', 'desc', 'contact_phone', 'contact_email', 'host_rso', 'event_type']

class AddCommentForm(forms.ModelForm):
    
    # def __init__(self, pk=None, *args, **kwargs):
    #     self.request = kwargs.pop('request', None)
    #     return super().__init__(*args, **kwargs)
    
    # def save(self, *args, **kwargs):
    #     kwargs['commit'] = False
    #     obj = super().save(*args, **kwargs)
    #     if self.request:
    #         obj.created_by = self.request.user
    #     obj.save()
    #     return obj

    class Meta:
        model = Comment
        fields = ['text', 'rating', 'event']

events/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.contrib.auth import login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView
from django.shortcuts import render, redirect
from django import forms
from .forms import MyUserCreationForm, EditUserForm, AddEventForm, AddCommentForm
from .models import University, User, Event, RSO, Comment

# Create your views here.
class WelcomeView(TemplateView):
    template_name = 'events/welcome.html'

class RegistrationView(FormView):
    template_name = 'events/register.html'
    form_class = MyUserCreationForm
    
    def form_valid(self, form):
        form.save()
        username = form.cleaned_data.get('username')
        raw_password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=raw_password)
        login(self.request, user)
        return redirect('events:home')

class HomeView(LoginRequiredMixin, ListView):
    model = Event
    template_name = 'events/home.html'

class ViewUser(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'events/viewUser.html'

class EditUser(LoginRequiredMixin, UpdateView):
    model = User
    template_name = 'events/editUser.html'
    form_class = EditUserForm

class UniversityList(LoginRequiredMixin, ListView):
    model = University
    template_name = 'events/listUniversities.html'

class AddUniversity(UserPassesTestMixin, CreateView):
    model = University
    template_name = 'events/addUniversity.html'
    fields = ['name', 'location', 'desc', 'num_students']

    def test_func(self):
        return self.request.user.is_authenticated and self.request.user.perm_level == 'Superadmin'

    def form_valid(self, form):
        form.instance.superadmin = self.request.user
        return super().form_valid(form)

class ViewUniversity(LoginRequiredMixin, DetailView):
    model = University
    template_name = 'events/viewUniversity.html'

class EditUniversity(UserPassesTestMixin, UpdateView):
    model = University
    template_name = 'events/editUniversity.html'
    fields = ['name', 'location', 'desc', 'num_students']

    def test_func(self):
        return self.request.user.is_authenticated and self.request.user.pk == self.get_object().superadmin.pk

class AddEvent(UserPassesTestMixin, CreateView):
    model = Event
    template_name = 'events/addEvent.html'
    form_class = AddEventForm

    def test_func(self):
        return self.request.user.is_authenticated and (self.request.user.perm_level == 'Admin' or self.request.user.perm_level == 'Superadmin')
    
    def form_valid(self, form):
        form.instance.host = self.request.user
        return super().form_valid(form)

class ViewEvent(LoginRequiredMixin, DetailView):
    model = Event
    template_name = 'events/viewEvent.html'

class EditEvent(UserPassesTestMixin, UpdateView):
    model = Event
    template_name = 'events/editEvent.html'
    fields = ['host', 'time', 'location', 'university', 'name', 'category', 'desc', 'contact_phone', 'contact_email', 'host_rso', 'event_type']

    def test_func(self):
        return self.request.user.is_authenticated and self.request.user.pk == self.get_object().host.pk

class AddComment(LoginRequiredMixin, CreateView):
    model = Comment
    template_name = 'events/addComment.html'
    form_class = AddCommentForm

    # def get_form_kwargs(self):
    #     kwargs = {'initial': self.get_initial()}
    #     if self.request.method in ('POST', 'PUT'):
    #         kwargs.update({
    #             'data': self.request.POST,
    #             'files': self.request.FILES,
    #             'request': self.request
    #         })
    #     return kwargs
    
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['pk'] = self.request.GET.get('pk', None)
    #     # print(self.request.GET.get('pk', None))
    #     return context
    
    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

class EditComment(UserPassesTestMixin, UpdateView):
    model = Comment
    template_name = 'events/editComment.html'
    fields = ['text', 'rating']

    def test_func(self):
        return self.request.user.is_authenticated and self.request.user.pk == self.get_object().created_by.pk

class DeleteComment(UserPassesTestMixin, DeleteView):
    model = Comment
    template_name = 'events/deleteComment.html'
    success_url = reverse_lazy('events:home')

    def test_func(self):
        return self.request.user.is_authenticated and self.request.user.pk == self.get_object().created_by.pk

class RSOList(LoginRequiredMixin, ListView):
    model = RSO
    template_name = 'events/listRSOs.html'

class AddRSO(UserPassesTestMixin, CreateView):
    model = RSO
    template_name = 'events/addRSO.html'
    fields = ['name', 'num_students', 'university', 'admin']

    def test_func(self):
        return self.request.user.is_authenticated and (self.request.user.perm_level == 'Admin' or self.request.user.perm_level == 'Superadmin')

class ViewRSO(LoginRequiredMixin, DetailView):
    model = RSO
    template_name = 'events/viewRSO.html'

class EditRSO(UserPassesTestMixin, UpdateView):
    model = RSO
    template_name = 'events/editRSO.html'
    fields = ['name', 'num_students', 'university', 'admin']

    def test_func(self):
        return self.request.user.is_authenticated and self.request.user.pk == self.get_object().admin.pk

events/templates/events/addRSO.html
{% extends 'base.html' %}

{% block head %}
<title>Add RSO</title>
{% endblock %}

{% block body %}
<h1 class="display-3 text-center">Add RSO</h1>
<br>
<div class="container-fluid text-center">
    <form action="{% url 'events:addRSO' %}" method="POST">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {% for field in form %}
            <div class="fieldWrapper">
                {{ field.label_tag }}
                {{ field }}
                {% if field.help_text %}
                    {{ field.help_text }}
                {% endif %}
                {{ field.errors }}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-lg btn-secondary">Submit</button>
        <a href="{% url 'events:RSOs' %}" class="btn btn-lg btn-secondary">Back</a>
    </form>
    <br>
</div>
{% endblock %}

events/templates/events/addUniversity.html
{% extends 'base.html' %}

{% block head %}
<title>Add University</title>
{% endblock %}

{% block body %}
<h1 class="display-3 text-center">Add University</h1>
<br>
<div class="container-fluid text-center">
    <form action="{% url 'events:addUniversity' %}" method="POST">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {% for field in form %}
            <div class="fieldWrapper">
                {{ field.label_tag }}
                {{ field }}
                {% if field.help_text %}
                    {{ field.help_text }}
                {% endif %}
                {{ field.errors }}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-lg btn-secondary">Submit</button>
        <a href="{% url 'events:universities' %}" class="btn btn-lg btn-secondary">Back</a>
    </form>
    <br>
</div>
{% endblock %}

events/templates/events/editComment.html
{% extends 'base.html' %}

{% block head %}
<title>Edit Comment</title>
{% endblock %}

{% block body %}
<h1 class="display-3 text-center">Edit Comment</h1>
<br>
<div class="container text-center">
    <form action="{% url 'events:editComment' comment.pk %}" method="POST">
        {% csrf_token %}
        {% for field in form %}
            <div class="fieldWrapper">
                {{ field.label_tag }}
                {{ field }}
                {% if field.help_text %}
                    {{ field.help_text }}
                {% endif %}
                {{ field.errors }}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-lg btn-secondary">Submit</button>
        <a href="{% url 'events:viewEvent' comment.event.pk %}" class="btn btn-lg btn-secondary">Back</a>
    </form>
</div>
{% endblock %}

events/templates/events/editEvent.html
{% extends 'base.html' %}

{% block head %}
<title>Edit Event</title>
{% endblock %}

{% block body %}
<h1 class="display-3 text-center">Edit Event Information</h1>
<br>
<div class="container text-center">
    <form action="{% url 'events:editEvent' event.pk %}" method="POST">
        {% csrf_token %}
        {% for field in form %}
            <div class="fieldWrapper">
                {{ field.label_tag }}
                {{ field }}
                {% if field.help_text %}
                    {{ field.help_text }}
                {% endif %}
                {{ field.errors }}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-lg btn-secondary">Submit</button>
        <a href="{% url 'events:viewEvent' event.pk %}" class="btn btn-lg btn-secondary">Back</a>
    </form>
</div>
{% endblock %}

events/templates/events/editRSO.html
{% extends 'base.html' %}

{% block head %}
<title>Edit RSO</title>
{% endblock %}

{% block body %}
<h1 class="display-3 text-center">Edit RSO Information</h1>
<br>
<div class="container text-center">
    <form action="{% url 'events:editRSO' rso.pk %}" method="POST">
        {% csrf_token %}
        {% for field in form %}
            <div class="fieldWrapper">
                {{ field.label_tag }}
                {{ field }}
                {% if field.help_text %}
                    {{ field.help_text }}
                {% endif %}
                {{ field.errors }}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-lg btn-secondary">Submit</button>
        <a href="{% url 'events:viewRSO' rso.pk %}" class="btn btn-lg btn-secondary">Back</a>
    </form>
</div>
{% endblock %}

events/templates/events/editUniversity.html
{% extends 'base.html' %}

{% block head %}
<title>Edit University</title>
{% endblock %}

{% block body %}
<h1 class="display-3 text-center">Edit University Information</h1>
<br>
<div class="container text-center">
    <form action="{% url 'events:editUniversity' university.pk %}" method="POST">
        {% csrf_token %}
        {% for field in form %}
            <div class="fieldWrapper">
                {{ field.label_tag }}
                {{ field }}
                {% if field.help_text %}
                    {{ field.help_text }}
                {% endif %}
                {{ field.errors }}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-lg btn-secondary">Submit</button>
        <a href="{% url 'events:viewUniversity' university.pk %}" class="btn btn-lg btn-secondary">Back</a>
    </form>
</div>
{% endblock %}

events/templates/events/editUser.html
{% extends 'base.html' %}

{% block head %}
<title>Edit User Profile</title>
{% endblock %}

{% block body %}
<h1 class="display-3 text-center">Edit Your Information</h1>
<br>
<div class="container text-center">
    <form action="{% url 'events:editUser' user.pk %}" method="POST">
        {% csrf_token %}
        {% for field in form %}
            <div class="fieldWrapper">
                {{ field.label_tag }}
                {{ field }}
                {% if field.help_text %}
                    {{ field.help_text }}
                {% endif %}
                {{ field.errors }}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-lg btn-secondary">Submit</button>
        <a href="{% url 'events:viewUser' user.pk %}" class="btn btn-lg btn-secondary">Back</a>
    </form>
</div>
{% endblock %}

events/templates/events/home.html
{% extends 'base.html' %}

{% block head %}
<title>Home</title>
{% endblock %}

{% block body %}
<h1 class="display-3 text-center">Events</h1>
<br>
<ul class="container-fluid text-center">
    {% if request.user.perm_level != 'Student' %}
        <a class="btn btn-lg btn-secondary" href="{% url 'events:addEvent' %}">Add an Event</a>
    {% endif %}
    <br><br>
    <h2 class="display-5 text-center">Public Events:</h2>
    {% for event in object_list %}
        {% if event.event_type == 'Public' %}
            <li><a class="mx-auto" href="{% url 'events:viewEvent' event.pk %}">{{ event.name }}</a></li>
        {% endif %}
    {% endfor %}
    <br>
    <h2 class="display-5 text-center">RSO Events:</h2>
    {% for event in object_list %}
        {% if event.event_type == 'RSO' and event.host_rso in request.user.rsos.all %}
            <li><a class="mx-auto" href="{% url 'events:viewEvent' event.pk %}">{{ event.name }}</a></li>
        {% endif %}
    {% endfor %}
    <br>
    <h2 class="display-5 text-center">Private Events:</h2>
    {% for event in object_list %}
        {% if event.event_type == 'Private' and event.university.pk == request.user.university.pk %}
            <li><a class="mx-auto" href="{% url 'events:viewEvent' event.pk %}">{{ event.name }}</a></li>
        {% endif %}
    {% endfor %}
    <br>
</ul>
{% endblock %}

events/templates/events/listRSOs.html
{% extends 'base.html' %}

{% block head %}
<title>RSO List</title>
{% endblock %}

{% block body %}
<h1 class="display-3 text-center">RSOs</h1>
<br>
<ul class="container-fluid text-center">
    {% if request.user.perm_level != 'Student' %}
        <a class="btn btn-lg btn-secondary" href="{% url 'events:addRSO' %}">Add an RSO</a>
    {% endif %}
    {% for rso in object_list %}
        <li><a href="{% url 'events:viewRSO' rso.pk %}">{{ rso.name }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

events/templates/events/login.html
{% extends 'base.html' %}

{% block head %}
<title>Login</title>
{% endblock %}

{% block body %}
<h1 class="display-3 text-center">Login</h1>
<br><br><br>
<form class="text-center" method="post" action="{% url 'events:login' %}">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="fieldWrapper">
        {{ form.username.errors }}
        {{ form.username.label_tag }}
        {{ form.username }}
    </div>
    <div class="fieldWrapper">
        {{ form.password.errors }}
        {{ form.password.label_tag }}
        {{ form.password }}
    </div>
    <br>
    <button class="btn btn-lg btn-secondary col-auto" type="submit">Login</button>
    <a href="{% url 'events:welcome' %}" class="btn btn-lg btn-secondary col-auto">Back</a> 
</form>
{% endblock %}

events/templates/events/logout.html
{% extends 'base.html' %}

{% block head %}
<title>Logout</title>
{% endblock %}

{% block body %}
<h1>Buh bye</h1>
{% endblock %}

events/templates/events/viewRSO.html
{% extends 'base.html' %}

{% block head %}
<title>RSO Profile</title>
{% endblock %}

{% block body %}
<h1 class="display-3 text-center">RSO Information</h1>
<br><br><br>
<div class="container-fluid text-center col-auto">
    <p class="h3">Name: {{ rso.name }}</p>
    <p class="h3">Number of Students: {{ rso.num_students }}</p>
    <p class="h3">University: {{ rso.university }}</p>
    <p class="h3">Admin: {{ rso.admin }}</p>
    <p class="h3">Active? {{ rso.is_active }}</p>
    <br>
    {% if request.user.pk == rso.admin.pk %}
        <a href="{% url 'events:editRSO' rso.pk %}" class="btn btn-lg btn-secondary">Edit</a>
    {% endif %}
</div>
{% endblock%}

events/templates/events/viewUniversity.html
{% extends 'base.html' %}

{% block head %}
<title>University Profile</title>
{% endblock %}

{% block body %}
<h1 class="display-3 text-center">University Information</h1>
<br><br><br>
<div class="container-fluid text-center col-auto">
    <p class="h3">Name: {{ university.name }}</p>
    <p class="h3">Location: {{ university.location }}</p>
    <p class="h3">Description: {{ university.desc }}</p>
    <p class="h3">Number of Students: {{ university.num_students }}</p>
    <p class="h3">Superadmin: {{ university.superadmin }}</p>
    <br>
    <a href="{% url 'events:editUniversity' university.pk %}" class="btn btn-lg btn-secondary">Edit</a>
</div>
{% endblock%}

events/templates/events/welcome.html
{% extends 'base.html' %}

{% block head %}
<title>Welcome!</title>
{% endblock %}

{% block body %}
<br><br><br>
<h1 class="display-3 text-center">Welcome to the College Event Website!</h1>
<main class="inner cover text-center">    
    <br><br>
    <a href="{% url 'events:login' %}" class="btn btn-lg btn-secondary">Login</a>
    <a href="{% url 'events:register' %}" class="btn btn-lg btn-secondary">Register</a>
</main>
{% endblock%}